#ifndef _BLE_MESH_DEFINITIONS_H_
#define _BLE_MESH_DEFINITIONS_H_


#define ERROR esp_err_t
#define DEVICE_NAME "LED server"
#define CID_ESP 0x02E5

// Model identification numbers.
#define ESP_BLE_MESH_LED_SERVER_MODEL 0x0001


// OP codes for custom LED server.
#define ESP_BLE_MESH_LED_SERVER_MODEL_OP_CONFIG ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
#define ESP_BLE_MESH_LED_SERVER_MODEL_OP_SET ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
#define ESP_BLE_MESH_LED_SERVER_MODEL_OP_STATUS ESP_BLE_MESH_MODEL_OP_3(0x02, CID_ESP)

#endif //_BLE_MESH_DEFINITIONS_H_